[package]
name = "drivechain-eth"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
drivechain-c = { git = "https://github.com/nchashch/drivechain-c", rev = "b649a05fe7d1a9a474453fbad618950b060d59ee" }
