[package]
name = "drivechain-eth"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
drivechain-c = { git = "https://github.com/nchashch/drivechain-c", rev = "297fc95d16b1b06f6251155728f96ec677e4a79c" }
